config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "blogs#index"
  resources :blogs do
    collection do
      get :each_title
    end
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :genre

  has_one_attached :image
  belongs_to :user
  with_options presence: true do
    validates :title
    validates :content
    validates :genre_id
  end
  has_rich_text :content

end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    { id: 1, name: 'テクニカル' },
    { id: 2, name: 'ファンダメンタル' },
    { id: 3, name: '書籍' },
    { id: 4, name: '思ったこと' },
    { id: 5, name: '相談質' },
  ]

  include ActiveHash::Associations
  has_many :blogs
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  has_many :blogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :authenticate_user!, only: [:new,:create]

  def index
   if root_path
    @blogs = Blog.where(genre_id: params[:genre_id]).order(created_at: "DESC")
   end
  end

  def new
    @blog = Blog.new
  end

  def create
    message = Blog.create! params.require(:blog).permit(:title, :content,:image,:genre_id).merge(user_id: current_user.id)
    redirect_to root_path
  end

  def show
    @blog = Blog.find(params[:id])
    render json:{blog: @blog}
  end
  private
  def blog_params
    params.require(:blog).permit(:title,:content,:image,:genre_id).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 100, 100 ] : [ 1024, 768 ]) %>
  <% end %>
  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/blogs/_blog.html.erb
<%= @blogs.each do |blog|%>
<%= blog.content%>
<%end%>

app/views/blogs/index.html.erb
  <div class="d-flex bd-highlight blog-main">
    <div class="p-2 bd-highlight main-left">
      <% @blogs.each do |blog|%>
        <div class="border sub-blog" id="blog" data-id=<%= blog.id%>>
          <strong><%= blog.title%></strong>
          <span class="sub-blog-content"><%= blog.content%></span>
          <div class="time"><%= l blog.created_at%></div>
        </div>
      <% end %>
      <%= link_to "new", new_blog_path%>
    </div>
    <div class="p-2 flex-grow-1 bd-highlight">
      <div class="border main-right" id ="blog-detail">
      左のボックスから記事を選んでね
      </div>
    </div>
  </div>

app/views/blogs/new.html.erb
<%= form_with model:@blog,url:blogs_path, local: true do |form|%>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <%= form.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"genre-select"}) %>

  <div class='field'>
    <%= form.rich_text_area :content %>
  </div>
 
    <%= form.submit %>

<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="head">
        <p><%=link_to "タイトル", root_path%></p>
        <p>今日現在：5,000</p>
      </div>
    </header>
    <div class="container">
      <div class="sub-header">
<nav class="navbar navbar-light ">
  <form class="form-inline">
    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">検索</button>
  </form>
</nav>
        <div class="blog-genre-btn">
          <button type="button" class="btn btn-secondary" onclick="location.href='/?genre_id=1'">テクニカル</button>       
          <button type="button" class="btn btn-secondary" onclick="location.href='/?genre_id=2'">ファンダメンタル</button>        
          <button type="button" class="btn btn-secondary" onclick="location.href='/?genre_id=3'">書籍</button>        
          <button type="button" class="btn btn-secondary" onclick="location.href='/?genre_id=4'">思ったこと</button>   
          <button type="button" class="btn btn-secondary" onclick="location.href='/?genre_id=5'">相談室</button>   
        </div>     
      </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <%= yield %>
  </body>
</html>